# Site settings
title: The Pan Protocol - Securing the Digital Grove
email: iwschisel@gmail.com
description: "Welcome to The Pan Protocol: Securing the Digital Grove, a blog dedicated to my journey through the ever-evolving world of cybersecurity. As I navigate the complexities and challenges of digital security, I share my personal experiences, insights, and learning. From the foundational steps of IT to advanced cybersecurity strategies, join me as I uncover the mysteries of protecting the digital landscape and develop my own protocols for securing the cyber realm. Follow along for practical advice, project updates, and reflections on the path to becoming a skilled cybersecurity professional."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TheGreatGodPan.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

# Author settings
author:
  name: Ian Schisel
  bio: IT Specialist and Cybersecurity Enthusiast
  avatar: /assets/images/avatar.jpg

# Social links
social:
  github: https://github.com/yourgithubusername
  linkedin: https://www.linkedin.com/in/yourprofile
  twitter: https://twitter.com/yourhandle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: pretty

# Exclude
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ian Schisel"
