# Site settings
title: My Cybersecurity Journey
email: iwschisel@gmail.com
description: A blog documenting my journey and projects in IT and cybersecurity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TheGreatGodPan.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

# Author settings
author:
  name: Ian Schisel
  bio: IT Specialist and Cybersecurity Enthusiast
  avatar: /assets/images/avatar.jpg

# Social links
social:
  github: https://github.com/yourgithubusername
  linkedin: https://www.linkedin.com/in/yourprofile
  twitter: https://twitter.com/yourhandle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: pretty

# Exclude
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
